[server]
# 서버 설정
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200

[browser]
# 브라우저 설정
gatherUsageStats = false

[theme]
# 다크 테마 설정
base = "dark"
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[client]
# 클라이언트 설정
showErrorDetails = false
toolbarMode = "minimal" 